<x-app-layout>
    <x-slot name="header"><div><h2 class="text-lg font-semibold text-slate-900">Detalhes do Agente</h2><p class="text-xs text-slate-500">Diagnóstico da instalação</p></div></x-slot>

    <x-pw.page-header :title="$agente->machine_name" :description="($agente->empresa?->nome_fantasia ?: $agente->empresa?->razao_social)">
        <x-slot name="actions"><x-pw.button :href="route('master.agentes.index')" variant="secondary">Voltar</x-pw.button></x-slot>
    </x-pw.page-header>

    <div class="grid gap-5 lg:grid-cols-3">
        <x-pw.card><p class="text-xs font-semibold uppercase text-slate-400">Status</p><div class="mt-3"><x-pw.badge :variant="$agente->online ? 'success' : 'danger'">{{ $agente->online ? 'Online' : 'Offline' }}</x-pw.badge></div><dl class="mt-5 space-y-3 text-sm"><div><dt class="text-slate-500">Versão</dt><dd class="font-medium text-slate-900">{{ $agente->agent_version ?: '—' }}</dd></div><div><dt class="text-slate-500">Último contato</dt><dd class="font-medium text-slate-900">{{ $agente->last_seen_at?->format('d/m/Y H:i:s') ?? 'Nunca' }}</dd></div><div><dt class="text-slate-500">Última sincronização</dt><dd class="font-medium text-slate-900">{{ $agente->last_sync_at?->format('d/m/Y H:i:s') ?? 'Nunca' }}</dd></div></dl></x-pw.card>
        <x-pw.card><p class="text-xs font-semibold uppercase text-slate-400">Computador</p><dl class="mt-5 space-y-3 text-sm"><div><dt class="text-slate-500">Sistema</dt><dd class="font-medium text-slate-900">{{ trim(($agente->os_name ?? '').' '.($agente->os_version ?? '')) ?: '—' }}</dd></div><div><dt class="text-slate-500">IP local</dt><dd class="font-medium text-slate-900">{{ $agente->local_ip ?: '—' }}</dd></div><div><dt class="text-slate-500">IP público</dt><dd class="font-medium text-slate-900">{{ $agente->public_ip ?: '—' }}</dd></div></dl></x-pw.card>
        <x-pw.card><p class="text-xs font-semibold uppercase text-slate-400">Licença</p><dl class="mt-5 space-y-3 text-sm"><div><dt class="text-slate-500">Código</dt><dd class="font-medium text-slate-900">{{ $agente->licenca?->codigo }}</dd></div><div><dt class="text-slate-500">Plano</dt><dd class="font-medium text-slate-900">{{ $agente->licenca?->plano?->nome ?: '—' }}</dd></div><div><dt class="text-slate-500">Vencimento</dt><dd class="font-medium text-slate-900">{{ $agente->licenca?->termina_em?->format('d/m/Y') ?? 'Sem vencimento' }}</dd></div></dl></x-pw.card>
    </div>

    <div class="mt-6"><x-pw.table-card title="Logs recentes"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50"><tr><th class="px-5 py-3 text-left font-semibold text-slate-600">Data</th><th class="px-5 py-3 text-left font-semibold text-slate-600">Evento</th><th class="px-5 py-3 text-left font-semibold text-slate-600">Nível</th><th class="px-5 py-3 text-left font-semibold text-slate-600">Mensagem</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($logs as $log)<tr><td class="px-5 py-4 text-slate-600">{{ $log->occurred_at?->format('d/m/Y H:i:s') }}</td><td class="px-5 py-4 font-medium text-slate-900">{{ $log->event }}</td><td class="px-5 py-4"><x-pw.badge :variant="$log->level === 'warning' ? 'warning' : ($log->level === 'error' ? 'danger' : 'info')">{{ ucfirst($log->level) }}</x-pw.badge></td><td class="px-5 py-4 text-slate-600">{{ $log->message }}</td></tr>@empty<tr><td colspan="4" class="px-5 py-10 text-center text-slate-500">Nenhum log registrado.</td></tr>@endforelse</tbody></table><x-slot name="footer">{{ $logs->links() }}</x-slot></x-pw.table-card></div>
</x-app-layout>
