<aside class="fixed inset-y-0 left-0 z-50 flex w-72 -translate-x-full flex-col bg-slate-900 text-white shadow-xl transition-all duration-200 lg:translate-x-0" :class="{'translate-x-0':sidebarOpen,'lg:w-20':sidebarCollapsed,'lg:w-72':!sidebarCollapsed}">
 <div class="flex h-16 items-center justify-between border-b border-slate-800 px-5"><a href="{{ route('dashboard') }}" class="flex items-center gap-3 overflow-hidden"><span class="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-blue-600 font-bold">PW</span><span class="text-lg font-bold" x-show="!sidebarCollapsed">PontoWeb</span></a><button class="rounded-lg p-2 text-slate-400 hover:bg-slate-800 hover:text-white lg:hidden" @click="sidebarOpen=false">✕</button></div>
 <nav class="flex-1 space-y-6 overflow-y-auto px-3 py-5">
  @php($link='flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition')
  <div class="space-y-1"><a href="{{ route('dashboard') }}" class="{{ $link }} {{ request()->routeIs('dashboard') ? 'bg-blue-600 text-white' : 'text-slate-300 hover:bg-slate-800 hover:text-white' }}"><span class="w-5 text-center">⌂</span><span x-show="!sidebarCollapsed">Dashboard</span></a></div>
  <div><p class="mb-2 px-3 text-[11px] font-semibold uppercase tracking-wider text-slate-500" x-show="!sidebarCollapsed">Cadastros</p><div class="space-y-1">
   @foreach([['empresas.*','empresas.index','Empresa','▣'],['departamentos.*','departamentos.index','Departamentos','▤'],['cargos.*','cargos.index','Cargos','◆'],['horarios.*','horarios.index','Horários','◷'],['escalas.*','escalas.index','Escalas','▦'],['funcionarios.*','funcionarios.index','Funcionários','♟']] as [$pattern,$route,$label,$icon])
   <a href="{{ route($route) }}" class="{{ $link }} {{ request()->routeIs($pattern) ? 'bg-blue-600 text-white' : 'text-slate-300 hover:bg-slate-800 hover:text-white' }}"><span class="w-5 text-center">{{ $icon }}</span><span x-show="!sidebarCollapsed">{{ $label }}</span></a>@endforeach
  </div></div>
  <div><p class="mb-2 px-3 text-[11px] font-semibold uppercase tracking-wider text-slate-500" x-show="!sidebarCollapsed">Ponto</p><div class="space-y-1">
   <a href="{{ route('ponto.index') }}" class="{{ $link }} {{ request()->routeIs('ponto.*') ? 'bg-blue-600 text-white' : 'text-slate-300 hover:bg-slate-800 hover:text-white' }}"><span class="w-5 text-center">◉</span><span x-show="!sidebarCollapsed">Batidas</span></a>
   <a href="{{ route('equipamentos.index') }}" class="{{ $link }} {{ request()->routeIs('equipamentos.*') ? 'bg-blue-600 text-white' : 'text-slate-300 hover:bg-slate-800 hover:text-white' }}"><span class="w-5 text-center">▥</span><span x-show="!sidebarCollapsed">Equipamentos</span></a>
  </div></div>
  @if(auth()->user()?->is_master)<div><p class="mb-2 px-3 text-[11px] font-semibold uppercase tracking-wider text-slate-500" x-show="!sidebarCollapsed">Plataforma</p><a href="{{ route('master.dashboard') }}" class="{{ $link }} {{ request()->routeIs('master.*') ? 'bg-blue-600 text-white' : 'text-slate-300 hover:bg-slate-800 hover:text-white' }}"><span class="w-5 text-center">★</span><span x-show="!sidebarCollapsed">Painel Master</span></a></div>@endif
 </nav>
 <div class="border-t border-slate-800 p-3"><button @click="sidebarCollapsed=!sidebarCollapsed" class="hidden w-full items-center gap-3 rounded-lg px-3 py-2 text-sm text-slate-400 hover:bg-slate-800 hover:text-white lg:flex"><span class="w-5 text-center">⇤</span><span x-show="!sidebarCollapsed">Recolher menu</span></button></div>
</aside>
